name: artifact file path test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo mkdir /mnt/test
          sudo chmod 777 /mnt/test
          touch /mnt/test/test.txt
          touch /mnt/test/test1.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-file              # ðŸ‘ˆ artifactname
          path: '/mnt/test/**'         # ðŸ‘ˆ 
