name: Download Linux Master Zip

on:
  workflow_dispatch:   # 手动触发

jobs:
  download_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Linux master.zip
        run: |
          curl -L -o master.zip https://github.com/torvalds/linux/archive/refs/heads/master.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-master-zip
          path: master.zip
