name: slowfetch all

on:
  schedule:
    # æ¯å¤© UTC 0:00 å’Œ 0:15 è¿è¡Œ
    - cron: "0 0 * * *"
    - cron: "15 0 * * *"
  workflow_dispatch:

jobs:
  fetch_logs:
    runs-on: ubuntu-latest
    env:
      ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      CF_COOKIE: ${{ secrets.CF_COOKIE }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Run log fetch script
        run: python sub/ordinaryfetcher.py 12

      - name: Logs
        uses: actions/upload-artifact@v4
        with:
          name: all-logs              # ğŸ‘ˆ artifact åç§°ï¼Œå¯è‡ªå®šä¹‰
          path: '**/*.json'         # ğŸ‘ˆ è¿™é‡Œæ¢æˆä½ å®é™…è¾“å‡ºæ–‡ä»¶æ‰€åœ¨çš„è·¯å¾„
